### ISSUE TITLE
We should have a code of conduct

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#113]
I've been concerned for a while that like many in the tech industry, we've got a bit of a diversity challenge at BrisJS. It's certainly not intentional and I don't think anyone means to exclude anybody, but especially now we're getting larger we need to implement a code of conduct to make sure everyone feels welcome.
## What is a Code of Conduct?

This is [probably one of my favourite articles on codes of conduct](http://rachelnabors.com/2015/09/01/code-of-conduct/) and it's worth a read, but here's an excerpt:

> Codes of Conduct are nothing new, but for the past couple of years they’ve been implemented increasingly at traditionally male-driven events like technology conferences as more women become active in those communities. Men and women ask for and implement these policies to help create safe, diverse spaces for all kinds of people including—but not limited to—women.

The crux of it, a code of conduct should contain:
1. statement of unacceptable behavior
2. how the policy will be enforced
3. how and to whom to make an incident report

As both an online and offline event, this document will need to apply to both physical and online behaviour.
## Prior art & implementation

The [CampJS code of conduct is quite good](http://vi.campjs.com/code-of-conduct.html), and looks to be based off the template at [confcodeofconduct.com](http://confcodeofconduct.com). I've put up a [diff of the two code of conducts](https://www.diffchecker.com/x1zwxyrq) (expires March 19).

I'd like to see us adopt the same CampJS code of conduct, with the latest updates to the first paragraph as per confcodeofconduct.com.
- I've prepared a **[proposed code of conduct](https://gist.github.com/AshKyd/551a37e14f2ff790ac49)**.
- I'm happy to be listed as a point of contact, and if anyone has any concerns in this are you're more than welcome to get in touch with me and I'll help sort them out.

While having a code of conduct isn't going to outright solve our diversity issues, I'm hoping it can be a step toward welcoming new folks to our community who otherwise might think twice about joining. 

Let me know what you think and if you have any concerns or suggestions for improvements.

**Comment by govpack** [comment]
I object to this form of social policing.

People ought to be able to sort out issues and grievances themselves, as they occur. Please give them some credit of being adults with manners that do not need extra rules and guidelines as to how to behave. 

I have not seen the slightest incident of anyone being rude ever at any of the brisJS events EVER. The diversity thing, is also a non issue, the group is OPEN and welcoming to ANYONE who wants to attend.

If you want a serene & sterile "Politically Correct World" with everyone second guessing, every second word, they say for fear of running afoul of the Thought & Word Police, then you have done a disservice to diversity and free speech. Honestly, there are enough rules already, I don't think we
help the human condition or human relations by adding more rules.

Being punitive and excluding, or casting someone out, is probably the worst thing we could do, because at that point you've lost them, without chance of correction, redemption etc, there's a missing step there along the lines of Luke 6:27-36...

```ruby 
“But to you who are listening I say: Love your enemies, do good to those who hate you, bless those who curse you, pray for those who mistreat you..."
````


Boxing people in, with more rules, just adds an unnecessary anxiety, we already live within Legal system that protects people from harassment and verbal threats etc. If anything, I feel more sympathy for those judged harshly and held excessively accountable for the stupid things they say. One thing I respect & appreciate about Nerd Culture is that people are free to be themselves. Please don't try to curb that enthusiasm with unnecessary rules.

If people don't know how to behave --- a code of conduct isn't going to help --- and for those who do treat others with manners & respect [which in my observation is: EVERYONE I've EVER met in the group, 100%]... then a code of conduct is an INSULT, that infantilises everyone involved. 

People have the right to be offended and then sort it out amongst themselves!!! That, in my view, is the best way for understanding and conflict resolution. But I've never been witness to a single tense moment, which may mean things are TOO sterile, sedated, or passive -- but that's up to the individuals involved!!! NOT some third party trying to occupy the non-existent moral high ground. 

Please do not try to make a "safe space" for precious politically correct snowflakes, who cannot or advocate for themselves (because they can, but they get more of a pernicious thrill out of getting others to punish "offenders" and most of their grievances enter quickly into the realm of the absurd). Or make out that something is wrong with us for not having a more "diversity" (whatever that means) since that's entirely up to the PERSONAL CHOICE and preferences of those who wish to attend, and is nothing anyone needs to feel guilty about [as we must respect other people's right NOT to be interested in javascript etc, and the bell curve of IQ probably excludes most people anyway, especially in this the Dumb Ass State, please respect people's RIGHT to be stupid & to say stupid things and not get too carried away with it]. Feminism and Political Correctness is destroying Europe, College Campuses, Comedy, free speech & healthy gender relations. Don't let it make any further inroads into our bit of Nerd Culture.

I have the sneaking suspicion that more people are going to be annoyed and irked by the application of unnecessary rules.... than those who think it is a good idea?? but i'm not sure how far this disease of Political Correctness has spread... Or if it's not going to be more a case of "some people want a Code of Conduct" and it's easy enough to do... so just add one!!! In which case I can just roll my eyes and become indifferent to the situation, and hope it doesn't spoil the thus far perfect record of decent interpersonal relations within the group (as far as i know). Then maybe we can rent an ethnically diverse crowd to make up for TOO many white males, who as we all know, are just the most EVIL, corrupt & GUILTY demographic of all time, and TOO many of them is a bad thing, and we need to absolve our white male guilt (what was it we did again??).... somehow by having it so: "whoever wants to come along CAN!!!" is a bad thing, giving rise to "a problem".

I don't think it is good to set up a "guards & prisoners" situation, or even hint that you need such stuff. I've heard that all such guidelines for decent human behaviour or codes of conduct can be reduced to a single word... "RESPECT".... why not have that as our code of conduct? and leave it up to others to be adult about things.

Thank you

**Comment by AshKyd** [comment]
Yay, thanks @govpack.

As you mentioned there haven't been any incidents at BrisJS we're aware of and I would certainly hope that would continue, but it becomes more of a concern as we get larger, branch out into things like pub meets, and eventually become part of a club or legal entity.

The big point we're trying to get across is to for people who have been burnt elsewhere, or might otherwise not come to our meetup to know that we have a place for them and that they are welcome. :)

**Comment by jwulf** [comment]
Be Awesome, and Make Others Feel Awesome.

**Comment by garrows** [comment]
How about: 
Be excellent to each other and party on dudes.
![coc](https://media.giphy.com/media/POekkUcKs16gg/giphy.gif)

Where will you publish our COC?

**Comment by iamkevinv** [comment]
If anyone finds this in the future and wonders what happened, please find the results have been in effect for some time, and currently live here: https://brisjs.org/#conduct
