### ISSUE TITLE
Reflex - higher-order FRP for front-end development

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#205]

**Comment by dalaing** [comment]
I don't know if BrisJS is keen on hearing about AltJS languages, but I could talk about doing front-end development with GHCJS and `reflex` if that would be of interest to the group.  If that were the case, I know a couple of people who could give a good talk on Purescript as well.

**Comment by dalaing** [comment]
These talks would also be relevant to #193

**Comment by AshKyd** [comment]
This sounds like fun, thanks for stepping up! Just a few questions:

1. Are you available for:
    - [ ] (a) August 14th
1. Which presentation block do you reckon this would be best suited to?
    - [ ] (a) 40min
    - [ ] (b) 20min
1. Please provide your Twitter handle (if available) so we can link from the meetup, website etc.

Let me know, and we can schedule you in. :)

FYI [information for speakers](https://bris.js.org/#present) is available on the website. Talks will be recorded for the website & YouTube channel, if you wish to opt out of this please let us know. Internet is not available at the venue, but if you need access to a 4G hotspot please let us know on the night.

**Comment by dalaing** [comment]
I think it would definitely be a 40 minute talk, and I could do it on the 14th.

Have there been any talks about Purescript before?  If not, I'll put some slides together to give a primer of ML-like syntax.  If the audience is likely to be thinking "Why functional?" I can put some slides in about that as well.

I'm giving a version of this talk to BFPG tomorrow night at The Precinct, but it's probably going to go a bit deeper into things since I don't have to motivate / explain those initial things as much.  If anyone is in the area and wants to check out the high-speed version of the talk, feel free to drop by :)

If the syntax might be a bridge to far for people, I can provide a link and some sample code at the end to [sodium-typescript](https://github.com/SodiumFRP/sodium-typescript), which just got released the other day and might look a bit more familiar to folks.  It also has a book that would probably help if people wanted to get started slowly.

Unfortunately (?) I don't have a twitter handle.

**Comment by dalaing** [comment]
Also - I have no idea what the BrisJS policy is on spruiking various things.

I'm currently working for Data61 at the Functional Programming Lab, and we're periodically doing free 3-day Intro to Functional Programming courses in Brisbane.  Am I alright to mention that during the talk, in case people like what they see / want to understand things a bit better / try some of this stuff out in anger?

If not it's no big deal, I just thought I'd ask so that I know either way.

**Comment by AshKyd** [comment]
That sounds good. I'll leave the final scheduling to @iamkevinv, but I think everything should be good to go.

Not having Twitter isn't a dealbreaker, though it is how we pull in speaker info to the BrisJS site so you just won't have a bio next to your video :)

Also, feel free to spruik those events. If you have any coming up, do let me know and I'll schedule some tweets as well.

**Comment by dalaing** [comment]
Is this likely to go ahead? 

If so, I'll really have to get cracking on retooling the talk for an audience that isn't as familiar with Haskell as BFPG :)  If not, I'm fine to mothball it for a while.

**Comment by iamkevinv** [comment]
Hey @dalaing - happy to have you next Monday :-) sorry for dragging out the suspense. We're all JS people so be kind to us - these other languages might seem scary! Heheh. Looking forward to it.

**Comment by AshKyd** [comment]
Good news, thanks @iamkevinv!

@dalaing, could I please get a title/synopsis we can use for the meetup :)

**Comment by dalaing** [comment]
Title:
Reflex - higher-order FRP for front-end development.

Synopsis:
There has been a lot of buzz about Functional Reactive Programming over the last few years.
Most of it has been about distant relatives of the original idea, which aren't anywhere near as powerful.

This talk will be about Reflex, a Haskell library which uses FRP for front-end development with great correctness, composability and performance.

Even if you're never going to touch Haskell with a ten-foot pole, the ideas should be interesting for those who have been following the various reactive technologies.

**Comment by dalaing** [comment]
@iamkevinv I'll be kind :)  I mostly just want to get across some of the ideas from the original conception of Functional Reactive Programming, since I think they're pretty handy for front-end development. 

If I have time, I'll try to work some `sodium-typescript` in - although it's not really something I'm set up for.  The syntax might be a bit more familiar, but I don't think it has some of the key features that Reflex has and I'd probably be able to fit less stuff in per slide.

**Comment by AshKyd** [comment]
Thanks very much for your talk, it was really eye opening! Do you have some slides/resources posted somewhere we could share with the meetup?

**Comment by dalaing** [comment]
I should have the slides up somewhere in a day or two - I'll let you know when they're ready.

**Comment by dalaing** [comment]
I've put the slides up [here](https://blog.qfpl.io/share/talks/intro-to-reflex-brisjs/).

**Comment by AshKyd** [comment]
Awesome thanks. I've added them to this page, the video will pop in when it's uploaded https://brisjs.org/#talk-189
