### ISSUE TITLE
Talk: Create, Debug and Deploy JavaScript Azure Functions

### ISSUE THREAD

**Issue by thiagospassos** [BrisJS/meetups#210]
Hi Kevin, 

I wanted to do a talk on Azure Functions with JavaScript.
-----------------------------------------------------
What's serverless? And why would you go serverless? Worry no more, these questions will be answered and I'll show you a great way to get started by using Azure Functions. 
You don't need to move all your applications to the cloud right now, you can start with bits and pieces without compromising your existing applications and see for yourself how great it can be.

**Comment by iamkevinv** [comment]
Hey @thiagospassos - is 20 mins sufficient or did you need a 40 slot? Were you available for next week if we have capacity to do that amount of time?

**Comment by thiagospassos** [comment]
Hi Kevin,

The time will drive how deep I can go. I'd probably prefer the 40min slot
though.

Cheers

**Comment by iamkevinv** [comment]
Hey @thiagospassos - best i could do is give you 30 since we're having two presenters up in the first half, but the 2nd presenter says they only need 10-15. Worth noting that we've had a couple of  presentations around serverless in the past few months but they were all AWS. So if you wanted to trim down anywhere, maybe reduce some info around what serverless is (by all means mention it at least) and focus more on doing it under azure and the like :)

**Comment by thiagospassos** [comment]
Cool.. no worries

**Comment by AshKyd** [comment]
Thanks for the talk @thiagospassos, was really interesting to see how the Azure platform does things.

Do you have your slides or any resources shared someplace we could link to?

**Comment by thiagospassos** [comment]
Hi Ash,

Thanks for having me. I actually wrote a blog post on the talk with demos,
the slide deck and the full video.

Here it is https://passos.com.au/azure-functions-net-ug-tour/

Cheers

**Comment by AshKyd** [comment]
Very cool, thanks a lot!

I've [updated the BrisJS site with your link](https://bris.js.org/#talk-185), and we'll get video up as soon as we can.

**Comment by thiagospassos** [comment]
Awesome... thank you very much.
