### ISSUE TITLE
Queensland Startup Precinct Space

### ISSUE THREAD

**Issue by garrows** [BrisJS/meetups#211]
There is an amazing space on Brunswick St mall capable of holding 220 people. It's a collaboration with RiverCity Labs and QLD gov. I've spoken to them and they are available most nights for $16/hour to run the air conditioning. 

I spoke to @iamkevinv tonight and he is interested in running a 2nd BrisJS. Opening the issue to kick off organisation. 

![](http://advance.qld.gov.au/assets/includes/images/precinct-photo2.jpg)

**Comment by garrows** [comment]
Oh and the internet is >100Mbps download and upload!

**Comment by iamkevinv** [comment]
Thanks for sharing this here mate :)  As i've dropped hints of to many close followers of BrisJS, we are consistently exceeding our capacity at Toowong now, so depending on availability of talks, we are intending to have two meetups per month, and have a name differentiation between from that venue to BrisJS West... and BrisJS East will be a new location TBA. This location at Brunswick St is being considered due to the large capacity and general newness (and of course @garrows is a valuable contact there).

**Comment by garrows** [comment]
Some good space details here https://sites.google.com/view/theprecinct/stair-stadium?authuser=0

**Comment by garrows** [comment]
FunCaptcha (my employer) is happy to sponsor the air conditioning, the staff person (we are a resident so as long as I go we dont have to pay a staff member fee) & help clean up to avoid the cleaning fee.

**Comment by MauriceButler** [comment]
Looks like a very cool space. :+1:

**Comment by johncmckim** [comment]
@garrows @iamkevinv  I work from RCL I can talk to people there about this if you like. It's a great space and internet is fantastic (380Mb/s ethernet & 100Mb/s wifi).

**Comment by triyuga** [comment]
+1 for this. Toowong is a bit inconvenient to commute to, for me at least, and I've heard others make the same excuse 😄
