### ISSUE TITLE
Single Page Applications with ASP.NET Core

### ISSUE THREAD

**Issue by JasonGT** [BrisJS/meetups#213]
In this talk, we'll look at using ASP.NET Core JavaScript Services to build single page applications using Angular, Aurelia, Knockout, React, React+Redux or Vue. Using this approach you can develop on Windows, Mac, or Linux using your preferred source code editor. I'll demonstrate server-side prerendering, webpack dev middleware, hot module replacement (HMR), efficient production builds and much more. You will walk away ready to create single page applications using your favourite client-side framework and ASP.NET Core.

_If possible, I would like to do this talk on Monday 7th of August. Thank you. :)_

**Comment by AshKyd** [comment]
Thanks for volunteering Jason, we don't get too much Microsoft tech at BrisJS. Just a few questions to get the ball rolling:

1. Due to CampJS being on the weekend earlier the meetup has been moved to the next week. Are you available for:
    - [ ] (a) August 14th
1. Which presentation block do you reckon this would be best suited to?
    - [ ] (a) 40min
    - [ ] (b) 20min
1. Please provide your Twitter handle (if available) so we can link from the meetup, website etc.

Let me know, and we can schedule you in. :)

FYI [information for speakers](https://bris.js.org/#present) is available on the website. Talks will be recorded for the website & YouTube channel, if you wish to opt out of this please let us know. Internet is not available at the venue, but if you need access to a 4G hotspot please let us know on the night.

**Comment by AshKyd** [comment]
Cheers. I've added you to the September meetup, but will let @iamkevinv get back to you with the final okay. :)

**Comment by AshKyd** [comment]
Hi @JasonGT, sorry for taking so much time to get back to you.

Having considered things I'm a little hesitant to put a non-Javascript talk in the headliner spot for the second month in a row. Would you be willing to either condense it to 20 mins or move it to October to space things out?

**Comment by JasonGT** [comment]
Hi Ash,


No worries, October suits me just fine. I'll modify the talk to ensure that BrisJS gets max value.


Jason


________________________________

**Comment by AshKyd** [comment]
Awesome, thanks @JasonGT. I've confirmed you for 40 mins in October.

Some supplementary info: [Information for speakers](https://bris.js.org/#present) is available on the website. Talks will be recorded for the website & YouTube channel, if you wish to opt out of this please let us know. Internet is not available at the venue, but if you need access to a 4G hotspot please let us know on the night.

**Comment by JasonGT** [comment]
Hey @AshKyd - I'd planned for the 2nd of October, but I now realise that's a public holiday. Any chance we can move my talk to November? I have family visiting on the 9th of October. Thx.

**Comment by AshKyd** [comment]
No probs, moved this one out to November :)

**Comment by iamkevinv** [comment]
Hi @JasonGT - are you confirmed for the meetup on Nov 6th? Doing email announcements monday night if everyone can give me their yes :) 👍  thanks.

**Comment by JasonGT** [comment]
Yes, thank you. :)

Sent from my iPhone

On 29 Oct 2017, at 23:01, Kevin Vanderbeken <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @JasonGT<https://github.com/jasongt> - are you confirmed for the meetup on Nov 6th? Doing email announcements monday night if everyone can give me their yes :) 👍 thanks.
