### ISSUE TITLE
BrisJS Workshop Events - JS101 / Node for Noobs / etc

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#223]
Workshops will get kicked off at BrisJS and informal hack days (#222) would come
along with them. JS101 and Node for Noobs will probably be some of the
first series - as those have been requested. I'll open a new BrisJS issue
to start getting feedback on that separate to this discussion.

Was going to start work on both in OCT after my wedding is done. Good to
start thinking about where and when and who stuff now.

Getting bringing in the [Brisbane Tech Newbies](https://www.meetup.com/Brisbane-Tech-Newbies/) and [NodeGirls Brisbane](http://nodegirls.com.au/brisbane.html)  and other groups into the JS Workshops and Hack days would be great as they are active and overlapping target audiences. I have a few contacts already, but opening this up wont hurt.

Please remember It's early days - but any feedback or interesting tips and ideas for us to focus on are a benefit.

**Comment by johncmckim** [comment]
@iamkevinv if you are looking for mentors I'd be interested in volunteering. I have some experience running workshops as part of my role at A Cloud Guru. I can also help develop content for the workshop.

Who is the target for this workshop? People that have no programming experience?

**Comment by iamkevinv** [comment]
I'd love to have you on the list @johncmckim - I expect there would be variations on the kinds of workshops in exposure to programming. This is some off the cuff ideation we can use as talking points:
 - "Learning to code with JS" - perhaps assume no code knowledge, teach some basic computer science concepts about algorithms, structure, and introduce JS as a language to make your first 'program' in some fashion.
 - "JS101" - Basics recapped, but then how to get things done in JS with the language features and ecosystem. Propper intro. Start frontend.
 - "Node for noobs" - specifically about server side JS, building on the previous again.

**Comment by johncmckim** [comment]
Those topics are really good. I like that there's a series of workshops so people could in theory progress through them.

The workshops we've run in the past try to teach through making something. For example, learning about Serverless through building a chatbot. It's good because people see a result at the end of it. They can go home saying I made x. We also try to make what they're building something novel or fun i.e. a game.

One idea could be building [Hotdog or not hotdog](https://www.youtube.com/watch?v=ACmydtFDTGs). Each workshop could build on the last (if you didn't attend previously the code would be provided). The end result being something a bit fun and silly, that can detect if an image is a hotdog or not.

Another thing I found helpful in our workshops was to have some advanced sections at the end of each lesson. There are always students that are naturally faster than others. Having the advanced lessons helps keep them engaged while other students take longer to complete the tasks.

**Comment by KimBurgess** [comment]
That would be a pretty fun project to work through. I'm not sure if it drifts from the JS focus too much, but you could continue with an extension workshop(s) that provides an intro to tensorflow too. Once you have the model you can bring it into the front-end with https://github.com/transcranial/keras-js.

Obligatory reference project here: https://medium.com/@timanglade/how-hbos-silicon-valley-built-not-hotdog-with-mobile-tensorflow-keras-react-native-ef03260747f3

**Comment by iamkevinv** [comment]
These are good ideas folks :-) thanks for keeping up the conversation and feel free to continue to think  about what your ideal workshop would be like if you were starting out 👍👍

**Comment by johncmckim** [comment]
That tensorflow blog post is really cool @KimBurgess. But, I'd worry that it might be a bit too complex for a beginner.

Calling an API like [AWS Rekognition](https://aws.amazon.com/rekognition/) or [Google Vision](https://cloud.google.com/vision/) would be a simpler way to achieve the AI element. It would also expose students to the concept using using a third-party API via an SDK.

You could setup a AWS or Google account for the entire class if you wanted to avoid having to teach students how to do that.
