### ISSUE TITLE
Remote Viewing of BrisJS meetup with WebRTC

### ISSUE THREAD

**Issue by shotlom** [BrisJS/meetups#27]
Hi there,
I'm moving away from BrisVegas and despite being a pretty inactive member, what I'll miss most are the BrisJS meetup sessions.

Wondering whether we could experiment with setting up WebRTC streaming so I can still dial in, and so other meetup groups around Australia can take a peek at the BrisJS awesomeness.

**Comment by iamkevinv** [comment]
As a simple update to this, we've been recording and working on a youtube page and google plus organisation page.  Once the video's have undergone a review and approval process from those who appear in them, they will be here:
https://www.youtube.com/channel/UC9Zts-dkDz0DBZ_f8ETgHcQ/featured

A Streaming presentation may still be an option for adhoc and cross meetup events.

**Comment by jwulf** [comment]
What about Rollcall? P2P WebRTC audio: https://github.com/mikeal/roll-call

**Comment by iamkevinv** [comment]
Another ping is that we're going to probably get regular youtube streaming in addition to formal event recordings. We just have to work out the hardware situation :)

**Comment by AshKyd** [comment]
I have a tripod & phone, and I'm happy to continue doing the livestream. We may need to request the Auto & General folks set up a wifi password each month though, as it expires regularly.

If all else fails I can probably do this on 4G depending on network congestion.

I'm going to close this one because I think this satisfies the original request :)
