### ISSUE TITLE
Jamie: Design hacks for developers

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#301]
Full name: 
Talk title: Design hacks for developers
Talk length: ~10 min
Talk synopsis for the mailouts etc:
Available month(s): November
Optional: your Twitter account to promote the talk:

**Comment by jamie-larchin** [comment]
Full name: Jamie Larchin
Talk title: Design hacks for developers
Talk length: ~10 min
Talk synopsis: Would you consider yourself reasonably ‘design savvy’? I’ve always loved design. But it wasn’t until mid-design degree that I fell in love with coding too. I’ve since found a career as a Front End Engineer, where I get to have the best of both worlds, building awesome user experiences across really cool products. I’d like to take you through how I observe and reason about design. This particular way of thinking is something I learnt a while back and it immediately became something I couldn’t “un-see”. So if you’re interested in adding some design hacks to your developer toolbox, let’s have some nerdy fun discussing all things web and design.
Available month(s): November
Optional: your Twitter account to promote the talk: jamielarchin__

**Comment by iamkevinv** [comment]
Wonderful, thanks!

**Comment by iamkevinv** [comment]
Hi @jamie-larchin - Apologies but due to text limits of meetup.com i had to shorten your blurb slightly... It now reads:
"Would you consider yourself reasonably ‘design savvy’? Jamie gets to design and build awesome user experiences across really cool products and will be taking you through how she observes and reasons about design - this thinking became something she couldn't "un-see". If you’re interested in adding some design hacks to your developer toolbox, come and have some nerdy fun discussing all things web and design."

If you'd like to make any edits from what i've put there i'm happy to update it on the meetup.com entry at anytime. :)

Thanks - looking forward to seeing you there!

**Comment by iamkevinv** [comment]
@jamie-larchin - If you have some resources you'd like to share with the audience, please feel free to share them here! Thanks again!
