### ISSUE TITLE
Recruitment Q&A

### ISSUE THREAD

**Issue by theharold9000** [BrisJS/meetups#314]
**Talk title:** Recruiting participants for a Q&A with a recruiter on recruitment.
**Talk length:** 10-20 Minutes (potentially lightning).
**Talk synopsis:** What tech is in demand? How do you ACTUALLY attract top developers? Which recruiters are actually good? All questions will be answered, you just have to ask them.
**Available month(s):** Every month.
**Optional:** @theharold9000

**Comment by iamkevinv** [comment]
hey @theharold9000 - sorry i haven't been in touch... i did promise to get you in a lineup, so how about May?

**Comment by theharold9000** [comment]
Hey @iamkevinv, only just got around to this. Happy to do something for this coming Monday? I can tailor the content around those FAQs as well :)

**Comment by iamkevinv** [comment]
Oh dude... sorry, kory approached me monday at node brisbane to get a lightning talk in... however...lets squeeze you on anyway...
Could you maybe give a 5 point / 5-ish minute lightning talk about those points we mentioned?
 - Tailored to JS devs because we're in spectacular demand.
 - What are current salary ranges for junior/mid/senior JS talent.
 - One main message to managers looking for js talent in bne.
 - Getting a JS job if you're transitioning to JS from another language
 - Landing a good job as a junior.

**Comment by iamkevinv** [comment]
is that a no or a yes @theharold9000?

**Comment by theharold9000** [comment]
Yep, count me in! I've get something together over the weekend

**Comment by iamkevinv** [comment]
Meetup page updated

**Comment by iamkevinv** [comment]
If you have the resources from your talk you can link, please do :)
