### ISSUE TITLE
10 most common cyber security mistakes developers make

### ISSUE THREAD

**Issue by MargaretDobson** [BrisJS/meetups#325]
Speaker Name: Margaret Dobson 
Talk title: 10 most common cyber security mistakes developers make 
Talk length: 20 min
Short Talk synopsis:
Available month(s): March
Optional: Linkedin: https://www.linkedin.com/in/margaret-dobson-2a1ab015b

**Comment by iamkevinv** [comment]
Potential talk synopsis:
If you're a developer with a non-trivial codebase, it can honestly be bewildering to think that we could have introduced a series of security holes without realising it. 
Maybe you're doing a self-security audit... what small things can we start with, in order to make meaningful change.
Margaret is here to help give us that boost to start our security learning journey.

**Comment by iamkevinv** [comment]
Thanks again for the great presentation yesterday! If you have any resources like your slides you can share with the group, please pop some links here 👍
