### ISSUE TITLE
Web Developer (Node.js + Frontend) 

### ISSUE THREAD

**Issue by cobbweb** [BrisJS/meetups#46]
We've got a JavaScript developer role available, graduates welcome too. More info here: https://jobs.github.com/positions/f76f3df2-bd83-11e4-888b-907d913db246

I can probably put together a talk on React or Webpack if you need speakers for the next meetup.

**Comment by kevdesign** [comment]
Always interested to hear React like stuff. Browserify and Webpack has been covered before to an extent, but there's always people who missed it the first time and there's always opportunity to learn something more, so that's welcome too. :-1: 
Please pop together a talk volunteer issue and i'd be happy to label it and work out a schedule with you accordingly! THANKS!

**Comment by iamkevinv** [comment]
Hi @cobbweb - Were you still interested in putting together a talk on the topics you mentioned?

**Comment by cobbweb** [comment]
Oh sorry @iamkevinv I totally forgot about this. That role has been filled btw.

I'd love to do a talk at some stage but I still haven't developed the proper confidence in React-land yet. I've only [built prototypes](https://github.com/cobbweb/isomorphic-react-example) around React with immutable data structures & other goodies, no hard production experience and lacking time.

**Comment by iamkevinv** [comment]
Well, in progress and learning talks are totally welcome :) have a think about it, and see if you can't just gift people with some open info. Also the new features and updates to webpack over the while had made it a candidate for a refresher talk at brisjs too... so most welcome to do that, or other topics too :)
