### ISSUE TITLE
Talk Submission: Customer Experience (CX)

### ISSUE THREAD

**Issue by dallasclark** [BrisJS/meetups#490]
Presenter Name: Dallas Clark
Title: What is Customer Experience (CX) and why it should be part of every team member's skillsets 
Presentation mode: in person

Throughout this talk, I will cover non-technical and technical scenarios that may have been solved properly if someone simply focused and understood what customer experience was.

The session is interactive and uses everyday products and services to explain each concept and how some easy, yet very clever solutions have solved some minor to major issues.

Clue: most solutions are not technical solutions.

After the session, every attendee should be able to identify areas of improvement that impacts the customer's experience.

**Comment by iamkevinv** [comment]
Thanks very much! When can you do this talk? The next one is Monday, or the following is Sept 4.

Since logistics aren't finalised - if we go ahead with Monday, it will still be streamed.
If we don't have the speakers for Monday, we will defer to Sept.
Sept is potentially in-person at A&G.

**Comment by dallasclark** [comment]
Hey @iamkevinv,

I would prefer to do this session in person at A&G please.

**Comment by dallasclark** [comment]
@iamkevinv I should have noted that the talk will take 35-40 minutes

**Comment by iamkevinv** [comment]
Hi @dallasclark,
Instead of the next week presentation... given we're aiming to have in-person events again, could you please confirm if you're available to present this at the October BrisJS? Seems like we also had the public holiday clash come up on Oct 2, So we'd be looking at Monday Oct 9th instead.
Why do i ask? Well, getting the sponsorship money organised is taking a little longer, and we'll miss our window by at least week. That week after, I will be unable to MC the events and handle the logistics. So we might end up making the next one a BrisJS social event in the city, and then re-launch in-person BrisJS with an even bigger bang.
Can you let me know asap? Thanks.

**Comment by dallasclark** [comment]
To confirm, 9th of October will be in person? If so, yes I can.

**Comment by theharold9000** [comment]
Hey @dallasclark, wanted to confirm that we're good to go for the 9th of October meetup being in person - really looking forward to your talk! Let us know if you run into any issues or have any questions :)

**Comment by dallasclark** [comment]
Thanks @theharold9000,

Looking forward to it!

**Comment by iamkevinv** [comment]
Thanks very much for making this happen mate! If you have links or resources you want to leave here, please feel free to reopen and add. Otherwise thanks again!

**Comment by dallasclark** [comment]
My pleasure, it was a lot of fun. I'll prepare another session in the near future.

Would you like me to share slides?

**Comment by iamkevinv** [comment]
You absolutely could if you like :)

**Comment by dallasclark** [comment]
[Customer Experience.pdf](https://github.com/BrisJS/meetups/files/13236260/Customer.Experience.pdf)
