### ISSUE TITLE
Forcing Factors: Adopting New Front-End Frameworks (presentation submission)

### ISSUE THREAD

**Issue by drpitman76** [BrisJS/meetups#504]
Talk title: Forcing Factors: Adopting New Front-End Frameworks

Talk length: 20 min

Talk synopsis:
To innovate, we must challenge the status quo. This interactive session makes the case for staying curious, daring to fail, exploring and  embracing new front-end frameworks, while providing a forum to discuss adoption triggers and barriers. I’ll explore why developers and companies should always check their assumptions and weigh factors like career growth, delivering value, and avoiding stagnation. It will encourage discussion on what forces or impedes change, from individual motivators to company roadblocks. Attendees will leave with a nuanced perspective on balancing innovation with pragmatism.

Available month(s): November, December 2023

**Comment by iamkevinv** [comment]
Thanks so much for your submission @drpitman76 :) 
November is looking pretty full already, but can you let me know just in case if you're available to present for this upcoming Nov 6? Otherwise, we'll definitely have a timeslot for you in the Dec meetup. I'll work out the final lineup and post back here of course. let me know!

**Comment by drpitman76** [comment]
I can be available as required, no problem and thanks for the opportunity!

**Comment by drpitman76** [comment]
Just a quick question from a newbie here... does this mean that I should show up on Monday with this presentation ready to go in case there is a space? Or will I be notified beforehand if I'll be on next week and assume that I won't be doing anything unless told otherwise before?

**Comment by iamkevinv** [comment]
No no nothing like that. You are off the hook, we can have you first up in Dec!

**Comment by iamkevinv** [comment]
Hi @drpitman76 - Can you confirm you will present on Monday 11th Dec? Thanks :)

**Comment by iamkevinv** [comment]
Sorry, i originally said 4th dec, but it was already set to 11th dec for availability reasons. It's Monday 11th.

**Comment by drpitman76** [comment]
I would prefer to do the ElementHTML one for December - I am happy to push this Forcing Factors one back to next year whenever you see a fit.

**Comment by iamkevinv** [comment]
Hi @drpitman76! Just trying to make sure I can lock in the next event in Feb - Given that I'm late to chase up everyone's confirmations for attendance I may resort to moving the event to 12 Feb instead of 5th Feb (also giving me time to fix up the drinks supply sponsorship). I am however asking everyone if they're available for both dates, so I can make a determination. Please let me know ASAP if you can do a presentation on either 5th Feb or 12th Feb, or March 11th? Thank you!

**Comment by drpitman76** [comment]
I can do this presentation on any of those dates, but the later dates are a bit better overall...

**Comment by iamkevinv** [comment]
The timeline is too tight to handle logistics and get everyone properly notified to get a good turn out, so i'm going to push it back to 12 Feb. I'll update meetup.com and start adding everyone's talk details there for the announcement :) I'll confirm you for the 12th Feb - locked in!

**Comment by iamkevinv** [comment]
Thanks again for your presentation for Feb! If you have any resources you want to share here that would be great :)

**Comment by drpitman76** [comment]
Just this link to the slides:  https://docs.google.com/presentation/d/1Quc-cmFwuK2C0zIiJi8SQCV__8LTgLWtz8cpXTreIEk/edit?usp=sharing
