### ISSUE TITLE
Talk: ("Hindsight" == 20-20 == false) stories from start up to scale up to big corporate you can maybe learn from

### ISSUE THREAD

**Issue by MrCeleryman** [BrisJS/meetups#508]
Presenter Name: Dan Mitchell
Talk title: ("Hindsight" == 20-20 == false) stories from start up to scale up to big corporate you can maybe learn from
Talk length: 20 or 30 min
Talk description:
Not written down yet but I imagine the talk would be is about working with JS throughout a startup to scale up to big company and how the decisions you make affect everything and pitfalls you should avoid/ things that aren’t important vs what’s important and explaining that from a business perspective and why everything can't be perfect and how to channel that energy into productive work that you can enjoy and still learn cool things.
Available month(s): Whenever just give me like a weeks notice or so 
Optional: www.linkedin.com/in/danmitchell1995

**Comment by iamkevinv** [comment]
No pressure @MrCeleryman, but a gap has opened in the schedule on this Monday 11th - are you keen to fill the 20min slot or too late notice?

**Comment by iamkevinv** [comment]
Correction... two gaps now... folks dropped out.

**Comment by iamkevinv** [comment]
Hi @MrCeleryman! Just trying to make sure I can lock in the next event in Feb - Given that I'm late to chase up everyone's confirmations for attendance I may resort to moving the event to 12 Feb instead of 5th Feb (also giving me time to fix up the drinks supply sponsorship). I am however asking everyone if they're available for both dates, so I can make a determination. Please let me know ASAP if you can do a presentation on either 5th Feb or 12th Feb, or March 11th? Thank you!

**Comment by iamkevinv** [comment]
Hi @MrCeleryman - Can i lock you in for presenting on Monday 11th March? Please let me know as soon as possible. I will be overseas on business during 4-8th march so my replies, and time to organise things will be limited :)

**Comment by iamkevinv** [comment]
Hello - should i close this submission? Or would you like to plan it for an upcoming month? Thanks @MrCeleryman

**Comment by iamkevinv** [comment]
Just closing this one for now as i've not heard back @MrCeleryman - in case you're keen to get it going again or a different talk, just reach out!
