### ISSUE TITLE
Front end developer @Sportsmed 

### ISSUE THREAD

**Issue by streetkid** [BrisJS/meetups#56]
Posting for a good friend of mine who's looking for some good front end developers.
They're using PHP Laravel + JavaScript.
Great perks and vibe, office at Newstead. Awesome management. Beautiful UI. 

Great product for sports (used by professional athletes), now that's one step closer to becoming a star yourself. Check link for more info:
http://sportsmedglobal.com/careers/front-end-developers/

Or please message me  / email at anonymlight ( at ) yahoo (.) com

**Comment by govpack** [comment]
@stretkid named desire;
"Great" would be good to prove with a demo!!

•Search · location:Brisbane
https://github.com/search?q=location:Brisbane &ref=advsearch&type=Users

## We've found 2,203 users, 

(and at least one in california) does fb or github have a open/looking for more work status field, I don't think so - that would be awesome.

If it's "Great" and Open Source then those people will find you and work for rewards other than money.
Professional "anything" detracts from what the rest of us do, they're too good, so why bother (i think they should all quit - because they're making us all fat). Sitting in a chair clicking buttons, or watching sport, has got to be one of the most unhealthy things one can do, the irony. 

in the mean time, ever thought of running a global distributed team in a contract based world?
smart people in poor places, can help you sling more code for less $$ ....

•Elance
https://mobile.elance.com/m/

•Hire Freelancers & Find Freelance Jobs Online - Freelancer
https://www.freelancer.com

•GetACoder - Quick & Easy Job Outsourcing. Outsource Your Job Today.
http://www.getacoder.com/

•Hire Freelancers & Find Freelance Jobs Online - Freelancer
https://www.freelancer.com

•Upwork - Hire Freelancers & Get Freelance Jobs Online (previously odesk)
https://www.upwork.com/

•Guru - Hire Quality Freelancers And Find Freelance Jobs
http://www.guru.com/

•Hire Freelance Software Developers from the Top 3%
http://www.toptal.com/


Or if you prefer to browse a book...
•More Awesome Than Money: Four Boys and Their Heroic Quest to Save Your Bacon - Jim Dwyer - 
https://books.google.com.au/books?id=rG1UAwAAQBAJ&pg=PT227&lpg=PT227&dq=more+awesome+than+money+file:pdf&source=bl&ots=FseY5_F1fv&sig=xCEb2OsOm2YkRVKIdMghnDvk7VU&hl=en&sa=X&ei=jgNPVbfWI-T2mQXn6YHADg&ved=0CEsQ6AEwCA#v=onepage&q&f=true

Also, would it be possible to be a man in woman's underwear and also apply, how would you know.
Gender bias duly noted, 'tho 95% correct, so whatever. If they had of put a woman on the moon then they would have said that...

•The first woman who went to the moon, but never returned. (how would we know)
https://www.youtube.com/watch?v=X3cgSOOFKCI

man has just got to become gender neutral (like dude has become in CA) then we can all be PC again without having to second check every second thing we say, which is just retarded. I don't identify as a "developer" or at least only mediocre or average, and front end has always sounded rude to me.

If your friend could translate this for me verbatim for me: 
•https://www.youtube.com/watch?v=u5FoZTaX8DA

then i would be happy to head up the sportsmed development team (but i would just do it by hiring online, as above, and seeing if we could get some open source play)

kind regards
govpack

**Comment by streetkid** [comment]
@govpack ,

 Apologies to people if it's uncomfortable and lack of details. The 'great' and 'beautiful' is my personal opinion from what I hear. I will post more details on requirements, etc when I get them from my friend. 

It's not my company so I am not the person to talk to about making things open source for this particular company and also why they choose to hire locals instead of freelancers. 

As for the gender bias issue, the 'be a man' was a joke referring to the meme, which I guess you're not famimliar yet. They would very much welcome applicants from any gender. I am a female dev myself. I've updated the listing so that it doesn't include the word 'man' in case anyone else misunderstands.

**Comment by kevdesign** [comment]
Apologies for any perceived overzealous clean-up/helpful-censorship on my part - I've just tried to keep this down from becoming too big a post since it's just a job callout, and we want these to be super on topic. Questions about the role specifically, or details about getting in contact are welcome, still of course. Thanks!

**Comment by govpack** [comment]
by "super on topic" do you mean blank? That was just me being interested, that is no longer the case. Apologies accepted, if you could recover that post, this is github after all, that should be easy right? lol

<img src="http://wheeler-centre-heracles.s3.amazonaws.com/wheeler-centre/assets/5a/2a9460a40111e4a21f4b408c032565/5c3112c0a40111e4807dbd4fb1c2850f_content_medium.jpg">

If someone says "good/brilliant/great" then some substance or a demo to prove it would be great.

I am all in favour of hiring and think more people should do it. When the job is filled please close the issue.

**Comment by govpack** [comment]
If someone has done a job posting, then: courteous, prompt, professional replies are the only way to go. In a public open forum like this, or where replies have been requested, you are going to get all sorts of people, some may have a sense of humour, opinions etc, it doesn't matter. Courteous, prompt, professional replies is the only way to go. The lack of such is a sign that those people are not organized or responsive or they don't care (i.e. I wouldn't want to have anything to do with that, that's why I'm not interested).

Delete is not so much of a big a deal, until someone does it to you. All I can say is: ask first. I would have probably redacted/deleted my post after so long without a reply. Now [links, information, history, sentiment, etc] it is lost forever. What will you delete next?  If you go into god mode like that, you're going to spook the cattle.

**Comment by govpack** [comment]
DELETE is not so much of a big a deal, until someone does it to you. All I can say is: ask first. I would have redacted/deleted my post after so long without a reply anyway, but now [links, information, history, sentiment, etc] it is lost forever. What will you delete next? Whatever you want to. If you go into god mode like that, you're going to spook the cattle.
