### ISSUE TITLE
Consider having meetups in the city

### ISSUE THREAD

**Issue by KoryNunn** [BrisJS/meetups#72]
I understand that the meetups are in toowong because it has parking, but how many people drive that aren't already coming from the city?

I've also talked to a number if people wont attend brisjs because it is out of their way, since they work in the city and live north side.
## Please respond with:
- Do you drive to Toowong?
- Would a CBD location be more convenient

**The Toowong venue is excellent, but it's quality is not relevant to the question at this stage**, as I'm trying to find out if an equivalently good venue in the CBD would be preferable. If many people prefer the location of the Toowong meetup, we won't bother looking for a good venue in the CBD.

**Comment by xwipeoutx** [comment]
It's not just north side, it's south side too - basically, non-westsiders have to go out of their way either by bus, train or car.  Train is probably easier for north siders than south.

I'd totally prefer a city-based one.

**Comment by MauriceButler** [comment]
+1 for city cause I work in the city.

Will mean finding new venue etc but I dont think this will be a huge deal. 

I would love to here from anyone who is -1 on this and why so we can evaluate the pros and cons.

**Comment by AshKyd** [comment]
I know this is something that's been talked about in the past, possibly as a multiple venue kind of thing. It's good the conversation's been restarted here. :)

Personally I like Toowong, but the city would definitely be more convenient for a lot of people.

**Comment by KoryNunn** [comment]
Have to say I'm not overly interested in two locations. Needs to be consistent for consistent attendance.

**Comment by iamkevinv** [comment]
This issue has come up in the past of course, and it's a complicated one.
I've surveyed this a while ago before investigating alternative venue's from the Toowong library meeting room. The results ultimately demonstrated that while there would be a group of interested parties who might join us from the city side, we would also loose those from other locations. Moving the location elsewhere at the time was a risk for no gain.
We needed better quality facilities and much bigger seating capacity to provide for the clear demand. With the connection we had - and thanks to efforts of our supporters and social wrangling - we were able to get the current Level 6 Toowong tower meeting space from A&G.
This is a pretty big deal, and it supports the growth in numbers and provides tools such as AV equipment - which is important for providing better quality recordings as we go too. The Toowong location provides free parking, bike racks for those cycling, a built in train station, and nearby bus stops. The venue supports up to 100 people, has a kitchen with large refrigeration facilities, provides large serviced mens and ladies bathrooms, and security. 
It was clearly a significant win to support our growth as well as my desired focus on quality. The sacrifice of being slightly west of the city was negated by obvious positives.
That brings us to alternate venue requests - Not a new topic, and I haven't forgotten. I understand that there's potential - and i'm more than happy to explore it. Building upon what I said above, to me, it makes the most sense to have more than one BrisJS venue, so that we can focus on adding and expanding, rather than replacing things we already have at a high quality.
Parallel streams will give us the ability to explore more content and more community reach. To be able to do this, we require a steady contribution of speakers and content. At the moment it is not always a simple task to arrange for enough speakers and content to fill a night. I'd like to see us fill at least 6 significant talks per month to be able to support a second venue. We need this 'consistently' to make it worthwhile, so we should see about 6-8 talks volunteered in the issues, where at this point we are well and truly far from this.
Want to replace it? We need parking (as close to free as possible) and public transport options, safety and security for the attendees, capacity for about 80-100 people, ability to provide food and drink, close by toilet facilities, and AV options with replication so that we can make sure everyone can see (i know we have struggled with this at the new venue but i swear we'll get that sorted).
Our focus needs to first be on the core manifesto of elevating the voices of JS. Making BrisJS an organisation that is strong, active, open, financially independent and has deep community and organisational ties in Brisbane, is worth the effort before we expand out and dilute what makes us great.
PS: GCJS needs some championing, and i've had some local people get in touch from that too so perhaps add your voices.

**Comment by KoryNunn** [comment]
Do we need car parks tho? I'm one of about 3 people I see who drive to Toowong.

Can we just skip the theory and give it a go one month? I can try find a venue.

**Comment by iamkevinv** [comment]
I wouldn't have expected that parking should be the most prominent thing
that I wrote about above - my point surrounds the combining factors, and
also touched on how much work when into the already recent change, which is
possibly easy to not realise. If we give up the current sponsorship for the
venue we risk not getting it back. Let's please table this for now, get
BrisJS sorted as a club so we have a stable base as an organisation and
then such issues can be openly addressed again. You are naturally welcome
to investigate options which could be suitable for us in the future though
if you're very keen.

**Comment by KoryNunn** [comment]
There was a lot to address, and I was on a phone.

I feel that the majority of what you said was around how A&G is a good venue, rather than whether a good venue in the city would be preferable. Obviously we wouldn't move if there wasn't an appropriate venue, but that's a discussion to be had if it is decided that the city is best for the majority of people.

I'm not suggesting we just up and abandon the A&G venue in the next few months, I'm just after some numbers around whether people would prefer a city venue. So far, the few responses so far point to yes.

On my "give it a go", maybe we could try a mid-month meetup at some stage in the next few months, to test the waters? I'm coming around on the multi-venue idea the more I think about it.

**Comment by iamkevinv** [comment]
Yeah mate, i wanted to put cards on the table and be open with the fact that there is a lot involved and sometimes a lot at stake. I was highlighting the level where things are at, and that we need to move up, not just break even and cause disruption. Loosing some only to gain others is of little use to a developing organisation i feel.

It's good that you have clarified/expanded some of your points. From your initial post, it was not clear that this is a numbers/information gathering exercise at all.
Lets start there. Research into some venues which can be organised is good regardless.

If i can have sponsors on board with running another event during the month, and there are talks which wont run the next month dry, then having an additional could be okay. Ultimately i was only going to look at it once it was clear that the volume of presentations could support us without sapping the next months talent pool. As long as there's confidence in this and the above i'm sure we can schedule a trial month some time in advance.

**Comment by AnnaGerber** [comment]
+1 for the new venue at Toowong - it is very nice

It was fantastic to see such a big group the first time we met there and it's been really great in terms of networking to have catering during intermission instead of going out to dinner as a group afterwards (where it was more difficult to get around to talk to more than a couple of people).

I drive to evening meetups for safety reasons, so I prefer Toowong from this perspective (not that there isn't parking available in the city, it's just that traffic makes it difficult to get there by 6 for those of us who don't work there).

**Comment by iamkevinv** [comment]
I've put the location question into the RSVP on meetup.com this month, as an information gathering exercise. I wish i could make it mandatory - but it might be interesting to get stats again since i last surveyed.

**Comment by jonny2k9** [comment]
I am happy with the current location. It is very easy to get to via public transport. The room is very nice as are the facilities. Parking is also easy.

That said, I am also happy if it moves into the city as a more central location for others.

**Comment by KoryNunn** [comment]
Could people post whether they drive or not, and if the CBD would be a more convenient location for them.

I'd say everyone is happy with the __venue__ at Toowong, but that's not what I'm asking.

**Comment by loklaan** [comment]
I'd prefer a more central location, like the CBD. I don't drive, and it takes me between 40mins - 1hr from home or work to get to Toowong. I know of a couple others also from around Newstead and West End, that don't come to the meetups because of the travel time.

A central location doesn't solve this for everyone, but could make the travel situation better.

**Comment by tomtomau** [comment]
I catch a bus and a train from Newstead to get to Toowong, which can be difficult to time correctly for a 6pm start. Not really one to complain about it, but city would be miles better for me.

**Comment by garrows** [comment]
I find the problem is getting home via public transport. By 8/9pm buses
have practically stopped running out there.

**Comment by nluo** [comment]
Yes I would prefer the CBD location too, last time i got home with Uber, can't be bother to take train back to central then change lines

**Comment by gazilla** [comment]
-1 for the city. I drive in from the burbs and the CBD is a major PITA. Finding parking is the main problem, paying for it is a minor aggrevation.

**Comment by stefan-o** [comment]
-1 city but I always can source a car park.

Timing is sometimes an issue, close to 5.

**Comment by govpack** [comment]
sounds like a debate about daylight savings, just do it already
the only ones who'll really vote are those who go

**Comment by govpack** [comment]
Do you drive to Toowong? No, i take a chauffeured, six carriage train. 
Would a CBD location be more convenient? what do you mean to strip clubs and the like? then yes

**Comment by shotlom** [comment]
The edge? Car parking, transport all hours, near cbd, beanbags!! ![image](https://cloud.githubusercontent.com/assets/398402/10990183/36622dfa-849c-11e5-9aab-4cdabca2211b.png)

**Comment by triyuga** [comment]
+1 for CBD venue! Toowong is a bit inconvenient to commute to, for me at least, and I've heard others make the same excuse 😄

**Comment by KoryNunn** [comment]
4 year revival!

There is a quazi-sibling meetup that runs in RCL every month: https://www.meetup.com/Node-Brisbane/

**Comment by iamkevinv** [comment]
FYI BrisJS 2 will be a thing. A 2nd Meetup in city. The node Meetup may actually be cobranded to be BrisJS 2 - but we need to work that out after I’m back.
