### ISSUE TITLE
Getting started with Ionic Framework for Apps

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#99]
@garrows has volunteered to give us a talk on http://ionicframework.com/ and some background on how it was used to win at Health Hack.

**Comment by garrows** [comment]
Here are my slides for my talk. http://slides.com/glenarrowsmith/ionic-intro

Hope people enjoyed it.

**Comment by jonny2k9** [comment]
@garrows It was really interesting. Makes it look so easy to make a cross platform mobile app. I was pondering while you were talking of the possibility of serving up different content when people connect to a server from different devices. E.g. if mobile, serve ionic app, otherwise serve desktop app. Would be handy for web based apps I would think.

**Comment by iamkevinv** [comment]
Thanks!
